name: Staging to DockerHub

on: [push]

jobs: 
  build:
   
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout files    
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and push Docker images
        id: betterstacy_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: deshanx/betterstacy:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commmand
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: deploy.sh
